import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import HireMe from "@/components/HireMe";
import { Toaster } from "sonner";

// Importing Poppins Thin 100
const poppins = Poppins({
  weight: ["100", "300", "400", "500"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Rabiyul islam Home page",
  description: "Generated by rabiyul islam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} font-sans`}>
        <Toaster richColors closeButton position="top-center" />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {/* Render children */}
          <div className="w-full  h-full inline-block z-0 lg:px-32 px-10 pb-5 pt-14">
            {children}
          </div>

          {/* HireMe component */}
          <div className="relative z-10">
            {/* <HireMe /> */}
            {/* Footer component */}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
