"use client";
import Logo from "./Logo";
import { ModeToggle } from "./ModeToggle";
import CustomLink from "./CustomLink";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Menu, ArrowUpRight } from "lucide-react";
const links = [["/", "Home"], ["/about", "About"], ["/projects", "Work"], ["/skills", "Skills"], ["/experiences", "Experience"]] as const;
const Header = () => <header className="fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-6"><div className="glass mx-auto flex max-w-[1360px] items-center justify-between rounded-2xl px-4 py-3 sm:px-5"><Logo /><nav className="hidden items-center gap-6 lg:flex">{links.map(([href, title]) => <CustomLink key={href} href={href} title={title} />)}</nav><div className="flex items-center gap-2"><ModeToggle /><a href="/contact" className="hidden items-center gap-1 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-slate-950 transition-transform hover:-translate-y-0.5 sm:flex">Let&apos;s talk <ArrowUpRight size={15}/></a><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="text-foreground lg:hidden"><Menu /></Button></SheetTrigger><SheetContent side="right" className="border-border bg-popover p-8"><Logo /><nav className="mt-12 flex flex-col gap-7">{[...links, ["/article", "Articles"], ["/contact", "Contact"]].map(([href, title]) => <CustomLink key={href} href={href} title={title} className="text-lg" />)}</nav></SheetContent></Sheet></div></div></header>;
export default Header;
