import { Metadata } from "next";
import { Code2, Server, Wrench, Lightbulb, ArrowUpRight, Layers3 } from "lucide-react";
export const metadata: Metadata = { title: "Skills", description: "Full stack engineering skills in React, Next.js, Node.js, NestJS, MongoDB, APIs, and product development.", alternates: { canonical: "/skills" } };
const skillsData = [
  { category: "Frontend engineering", icon: Code2, statement: "Interfaces that feel fast, clear, and alive.", level: "Core strength", percentage: "92%", skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "ShadCN UI", "JavaScript", "HTML5", "CSS3"], gradient: "from-cyan-300 via-primary to-blue-500", glow: "bg-cyan-400/15" },
  { category: "Backend systems", icon: Server, statement: "Reliable APIs and services that scale with the product.", level: "Production ready", percentage: "86%", skills: ["Node.js", "Express.js", "NestJS", "MongoDB", "REST APIs", "Microservices"], gradient: "from-emerald-300 via-green-400 to-teal-500", glow: "bg-emerald-400/15" },
  { category: "Developer toolkit", icon: Wrench, statement: "The practical infrastructure behind dependable delivery.", level: "Daily workflow", percentage: "82%", skills: ["Git", "Docker", "Redis", "RabbitMQ", "CI/CD", "Vercel", "Postman"], gradient: "from-violet-300 via-fuchsia-400 to-pink-500", glow: "bg-violet-400/15" },
  { category: "Product mindset", icon: Lightbulb, statement: "Technical decisions anchored in people and outcomes.", level: "Always improving", percentage: "90%", skills: ["Problem Solving", "Communication", "Teamwork", "Agile Delivery", "Critical Thinking"], gradient: "from-amber-200 via-orange-400 to-rose-500", glow: "bg-amber-400/15" },
];
const Skill = () => <main className="min-h-screen py-8"><section className="grid gap-8 border-b border-white/10 pb-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="eyebrow">Capabilities</p><h1 className="page-heading">Engineering range,<br/><span className="text-primary">product focus.</span></h1><p className="page-copy">A considered stack for taking a digital product from its first screen to the systems that keep it running.</p></div><div className="glass rounded-2xl p-6"><Layers3 className="text-primary"/><p className="mt-5 text-lg font-medium leading-7 text-slate-200">I work across the full product surface—visual polish, robust architecture, and the collaboration that turns ideas into releases.</p></div></section><section className="mt-10 grid gap-5 md:grid-cols-2">{skillsData.map((section, index) => { const Icon = section.icon; return <article key={section.category} className="glass group relative isolate min-h-[360px] overflow-hidden rounded-3xl p-6 transition-all duration-500 hover:-translate-y-2 hover:border-primary/50 sm:p-8"><div className={`absolute -right-14 -top-14 -z-10 h-48 w-48 rounded-full blur-3xl transition-transform duration-500 group-hover:scale-150 ${section.glow}`} /><div className="flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br ${section.gradient} text-slate-950 shadow-lg`}><Icon size={22}/></span><span className="text-xs font-semibold tracking-[.16em] text-slate-500">0{index + 1}</span></div><div className="mt-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{section.level}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-white">{section.category}</h2><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">{section.statement}</p></div><div className="mt-6 flex items-center gap-3"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full bg-gradient-to-r ${section.gradient}`} style={{ width: section.percentage }} /></div><span className="text-xs font-semibold text-slate-300">{section.percentage}</span></div><div className="mt-6 flex flex-wrap gap-2">{section.skills.map((skill) => <span key={skill} className="rounded-lg border border-white/10 bg-black/15 px-3 py-1.5 text-xs font-medium text-slate-300 transition-colors group-hover:border-white/20">{skill}</span>)}</div><ArrowUpRight className="absolute bottom-7 right-7 text-slate-600 transition-all group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-primary" size={20}/></article>; })}</section></main>;
export default Skill;
